# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'third-party/grantlee' : '@stable'
    'frameworks/kguiaddons': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/kiconthemes': '@latest'
    'frameworks/knewstuff': '@latest'
