[Icon Theme]
Name=DummyTheme
Name[ca]=Tema de prova
Name[ca@valencia]=Tema de prova
Name[cs]=FalesnyMotiv
Name[de]=DummyTheme
Name[fi]=Testiteema
Name[nl]=DummyThema
Name[pl]=FikcyjnyWystrój
Name[pt]=Tema de Testes
Name[pt_BR]=Tema de teste
Name[ru]=DummyTheme
Name[sk]=DummyTheme
Name[sl]=DummyTheme
Name[sv]=Testtema
Name[uk]=Фіктивна тема
Name[x-test]=xxDummyThemexx
Name[zh_CN]=虚拟主题

Directories=128x128/apps

[128x128/apps]
Size=128
Context=Applications
